language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
env:
  global:
    - R_MAX_NUM_DLLS=250
before_install:
 - wget -q -O - https://www.mongodb.org/static/pgp/server-3.2.pub | sudo apt-key add -
 - sudo apt-get --allow-unauthenticated update
 - sudo apt-get --allow-unauthenticated install libgsl-dev libsdl1.2-dev libreadline-dev imagemagick libfftw3-dev libudunits2-dev -y
install:
 - if [ `git branch | grep '* master' | wc -l` == 0 ]; then sed -i 's#\(dynverse/[^, ]*\)#\1@devel#' DESCRIPTION; fi
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'devtools::install_cran("covr")'
 - R -e 'devtools::install_github(c("r-lib/rlang", "tidyverse/ggplot2"))'
 - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = T, upgrade = T)'
after_success:
 - R -e 'covr::codecov()'
